### PR TITLE
Syntax highlighting for long lines

### PR DESCRIPTION
**Pull request by Aerijo**
This will allow the parser to find matches in long lines (eg. long paragraphs with only a few commands). It still does not allows over ~147 matches on a line though.

### CODE REVIEW

**Comment by Aerijo** [comment]
I use this one on my version with no problems. It really helps.

**Comment by Aerijo** [comment]
See my discussion here https://github.com/area/language-latex/issues/132 for some more details. Maybe a tip could be added to the README file suggesting `gramar-token-limit` if highlighting is off? (Also, please close that issue, it is resolved by this and got very much sidetracked)

**Comment by yudai-nkt** [comment]
This is a quite new feature, which I didn't know of, but seems fine. However, I prefer `false` rather than `no` (cf. [search result](https://github.com/search?l=CSON&q=limitLineLength&type=Code&utf8=%E2%9C%93) and [implementation](https://github.com/atom/first-mate/pull/88/commits/d1a39cf13e977298e5323d1fad97f29ca28f357a)).

**Comment by Aerijo** [comment]
Huh, I didn't realise you could do that thing with the search. But yeah, I'm fine with false (pretends I knew it was an option all along).

**Comment by edwinksl** [comment]
I suspect this particular change is causing my Atom to lag when editing LaTeX files. The lag is especially noticeable if I need to insert a pair of curly braces in a long sentence. Is there a good way to change `limitLineLength` to `true`?

**Comment by Aerijo** [comment]
I'm no expert on the internal working of syntax highlighting, but I wouldn't have thought this causes a noticeable issue. It will still only find a limited number of matches per line, and I have found the benefits far outweigh any lag I may have caused (at least on my computer). If it really is a problem, you can try inserting linebreaks to split it up.

I can't think of a good way to fix this in code though. I'll try and see if the value can be made optional, but I don't know if that would work.

In the meantime, you could edit the line directly in your local copy. You would have to change it with each update of this package, but that shouldn't be too often.

**Comment by edwinksl** [comment]
Thanks for the suggestions!

Yeah, I am not 100% certain the `limitLineLength` option is the problem, so I wanted to try setting it to `true` to see if it makes a difference. I will try editing `latex.cson` directly and see what happens.

**Comment by edwinksl** [comment]
Just a quick update: I have narrowed the lag down to the `bracket-matcher` package, which doesn't seem to perform well with long lines.

**Pull request merged**
