### PR TITLE
Throw away grammars about quotation marks

### LINKED ISSUE #87: Syntax Highlighting Bug
the following line messes up all subsequent syntax highlighting.

```
\DeclareGraphicsRule{.tif}{png}{.png}{`convert #1 `dirname #1`/`basename #1 .tif`.png}
```

with
without

### PR DESCRIPTION
**Pull request by yudai-nkt**
As proposed in #61, we are going to stop highlighting strings inside quotation marks.

Fix #87 and #61.

### CODE REVIEW

**Comment by Aerijo** [comment]
And the one below it too? It seems to be for French quoting.

**Comment by yudai-nkt** [comment]
Maybe not one, I guess. ;-)

**Comment by Aerijo** [comment]
I think this looks fine, is there something in particular we're waiting for?

**Comment by yudai-nkt** [comment]
Nothing particular, but I prefer not merging my PR myself. That being said, the owner seems to be off from the package, so I'll merge bunch of PR and release a new version before tackling major refactoring (some of them are listed in yudai-nkt/language-tex#10 and #97).

**Comment by Aerijo** [comment]
OK. I'll do my best to help when needed.

Also, are you still having trouble with the rogue `\t`'s? It took me a while to realise they were actual tab stops meant to be in the file: do a replace of the `\n`'s with an actual newline and `\t` with an actual tab and everything will look ten times cleaner.

**Comment by yudai-nkt** [comment]
It's discussed in #74 and fixed in #91.

**Pull request merged**
